server:
  port: 80

mongodb:
  host: mongodb://mongo
  name: things_db

things:
  host: localhost
  port: 80

rabbitmq:
  url: amqp://knot:knot@rabbitmq

logger:
  level: info
  syslog: false

expiration:
  time: 0